baseURL = "http://gendrot.com"
languageCode = "en-us"
title = "Sylvain Tech Blog"
theme = "hugo-theme-cleanwhite"


[outputs]
home = ["HTML", "RSS"]


[params]
  # header imgage and default image in post
  header_image = "img/home_bg.jpg"
  # Title of the page
  SEOTitle = "Sylvain Tech Blog"
  # Tag head-meta-description for SEO
  description = ""
  # Tag head-meta-keyword for SEO
  keyword = ""
  # Slogan of the website
  slogan = ""
  # 404 custom
  image_404 = "img/404-bg.jpg"
  title_404 = "Not Found :("

  # leancloud storage for page view counter in single page
  # add partial page_view_counter.html
  # leancloud chinese company (website in chinese XD )
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search in nav.html
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Show the aboutme in the sidebar
  about_me = true
  # Sidebar settings in sidebar.html
  sidebar_about_description = "DevOps, Linuxien et Cloud Addict DIY/Maker a mes heures perdues"
  sidebar_avatar = "img/aboutme.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
  # load he taxonomie tags in sidebar of homepage and bottom of singlepage
  featured_tags = true
  # minimun of pages of a tag to be shown
  featured_condition_size = 1

  # Baidu Analytics - if empty don't add it
  ba_track_id = ""

  # We need a proxy to access Disqus api in China - if empty don't add it
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles
  # add reward.html to single page
  reward = false
  # reward_guide = "如果这篇文章对你有用,请随意打赏"

  # if true, range .Site.Params.friend_link to create link with .href and .title
  friends = false
  # if true, range .Site.Params.bookmark_link to create link with .href or  and .title
  bookmarks = false
  # list of friend_link
  # [[params.friend_link]]
  # title = "Friend name"
  # href =  "https://example.com"
  # # list of bookmark_link
  # [[params.bookmark_link]]
  # title =  "Martin Fowler"
  # href =  "https://martinfowler.com"
  # additionnal link in the top menu
  # [[params.addtional_menus]]
  # title =  "ABOUT"
  # href =  "/top/about/"

  # [params.social]
  # rss            = true
#  email          = "youremail@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  # twitter       = "sgendrot"
  # linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  # # stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  # #instagram     = "full profile url in instagram"
  # github         = "https://github.com/yourgithub"
  # wechat         = "your wechat qr code image"
#  medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
